---

- name: VLANs, Layer 2 and Layer 3 interfaces configuration for spines using Enterprise SONiC resource modules
  hosts: spines
  gather_facts: no
  connection: httpapi
  tasks:
   - name: Configure VLANs
     dellemc.enterprise_sonic.sonic_vlans:
        config:
         - vlan_id: 701
         - vlan_id: 702
         - vlan_id: 703
         - vlan_id: 704
         - vlan_id: 705
        state: merged
     register: sonic_vlans_output
   - name: Configure Layer 2 interfaces
     dellemc.enterprise_sonic.sonic_l2_interfaces:
        config:
        - name: Eth1/1
          trunk:
            allowed_vlans:
              - vlan: 701
              - vlan: 702
              - vlan: 703
              - vlan: 704
        - name: Eth1/2
          trunk:
            allowed_vlans:
              - vlan: 701
              - vlan: 702
              - vlan: 703
              - vlan: 704
        state: merged
     register: sonic_l2_interfaces_output
   - name: Configure Layer 3 interfaces
     dellemc.enterprise_sonic.sonic_l3_interfaces:
        config:
        - name: Eth1/3
          ipv4:
            addresses:
              - address: 8.1.1.1/16
          ipv6:
            addresses:
              - address: 3333::1/16
        - name: Vlan 705
          ipv4:
            addresses:
              - address: 42.1.1.1/16
          ipv6:
            addresses:
              - address: 4242::1/16
        state: merged
     register: sonic_l3_interfaces_output

- name: VLANs for leafs
  hosts: leafs
  gather_facts: no
  connection: httpapi
  tasks:
   - name: Configure VLANs
     dellemc.enterprise_sonic.sonic_vlans:
        config:
         - vlan_id: 701
         - vlan_id: 702
         - vlan_id: 703
         - vlan_id: 704
        state: merged
     register: sonic_vlans_output
   - name: Configure Layer 2 interfaces
     dellemc.enterprise_sonic.sonic_l2_interfaces:
        config:
        - name: Eth1/2
          trunk:
            allowed_vlans:
              - vlan: 701
              - vlan: 702
              - vlan: 703
              - vlan: 704
        - name: Eth1/3
          access:
            vlan: 701
        - name: Eth1/4
          access:
            vlan: 702
        - name: Eth1/5
          access:
            vlan: 703
        - name: Eth1/6
          access:
            vlan: 704
        state: merged
     register: sonic_l2_interfaces_output
