---
# Copyright (c) 2024 Dell Inc. or its subsidiaries. All Rights Reserved
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

name: Collection Docs
concurrency:
  group: docs-push-${{ github.sha }}
  cancel-in-progress: true
on:
  push:
    # Temporary test branch: FIXME: delete the third one.
    branches:
      - main
      - stable-*
      - doc_workflow_update
    tags:
      - '*'
  # Run CI once per day (at 05:30 UTC)
  schedule:
    - cron: '30 5 * * *'
  # Allow manual trigger (for newer antsibull-docs, sphinx-ansible-theme, ... versions)
  workflow_dispatch:

jobs:
  build-docs:
    permissions:
      contents: read
    name: Build Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@main
    with:
      collection-name: dellemc.enterprise_sonic
      init-lenient: false
      init-fail-on-error: true
      squash-hierarchy: true
      init-project: Dellemc.Enterprise_Sonic Collection
      init-copyright: Dellemc.Enterprise_Sonic Contributors
      init-title: Dellemc.Enterprise_Sonic Collection Documentation
      init-html-short-title: Dellemc.Enterprise_Sonic Collection Docs
      init-extra-html-theme-options: |
        documentation_home_url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/branch/main/

  publish-docs-gh-pages:
    # for now we won't run this on forks
    # Adding the fork trigger for testing only.
    if: (github.repository == 'ansible-collections/dellemc.enterprise_sonic' or  github.repository == 'kerry-meyer/dellemc.enterprise_sonic')
    permissions:
      contents: write
      pages: write
      id-token: write
    needs: [build-docs]
    name: Publish Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-publish-gh-pages.yml@main
    with:
      artifact-name: ${{ needs.build-docs.outputs.artifact-name }}
      publish-gh-pages-branch: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

